### PR TITLE
Launch pod install programmatically

### PR DESCRIPTION
**Pull request by fabiopelosin**

### CODE REVIEW

**Comment by orta** [comment]
@segiddins @kylef  got an opinion on the value here?

**Comment by kylef** [comment]
Makes sense.

@fabiopelosin Is there any particular reason this was made as a PR? What specifically was your concerns when making this patch?

**Comment by kylef** [comment]
Since this has a "moderate" label and it's only ~5 lines of code, is this complete?

**Comment by segiddins** [comment]
I'd prefer to do this by invoking the `Install` command itself

**Comment by orta** [comment]
Is the feature worth doing? It's not worth waiting on a response from fabio ( love you buddy, hope you're rocking out :two_hearts: ) we could either re-do, or close.

**Comment by segiddins** [comment]
@kylef this should now be mergable!

**Pull request merged**
